version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mariadb:10.6.7'
    environment:
      MARIADB_PASSWORD: password123
      MYSQL_DATABASE: main
    ports:
      - '3306'
  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
  ###< symfony/mailer ###
###< doctrine/doctrine-bundle ###
