version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mariadb:10.6.7'
    environment:
      restart: always
      MYSQL_DATABASE: main
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    ports:
      - '3306'
  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
  ###< symfony/mailer ###
###< doctrine/doctrine-bundle ###
